# Python Cheatsheet

This cheatsheet is based on the huge notebook sent by the tutor.

- Ctrl  + Enter
- Shift + Enter
- Alt   + Enter

In [5]:
### NO NEED TO PRINT()
s = 'Hello World'
s

'Hello World'

TeX Syntax [https://en.wikibooks.org/wiki/LaTeX/Mathematics  
Magics     [https://ipython.readthedocs.io/en/stable/interactive/magics.html

### Useful data structures

**List**: homogenous, heterogenous

**Tuple**: Created by ',': 4,5,6. **See Named Tuples: https://docs.python.org/3/library/collections.html#collections.namedtuple**

**Range**: Constant space (start, stop, step are saved in memory) for any length. [a, b)

**Strings**: """Multiline string (no \ needed)"""

**Set and frozenset**: unordered (no slicing and []) set objects. Frozen is immutable => can be used as a dictionary key.

**Dictionaries**:

In [7]:
example_dict = {1: 2}
print(example_dict)
example_dict[1.0] = 3
print(example_dict)

# примеры создания dict
a = dict(one=1, two=2, three=3)
b = {'one': 1, 'two': 2, 'three': 3}
c = dict(zip(['one', 'two', 'three'], [1, 2, 3]))
d = dict([('two', 2), ('one', 1), ('three', 3)])
e = dict({'three': 3, 'one': 1, 'two': 2})
f = dict({'one': 1, 'three': 3}, two=2)
print(a == b == c == d == e == f)

# Итерация по dict
users = {"Andy": "Inactive", "Rayan": "Active"}
for usr, status in users.copy().items():        ## Items gives elements
    if status == "Inactive":
        del users[usr]
print(users)

{1: 2}
{1: 3}
True


### enumerate()

In [7]:
for idx, val in enumerate( ("NASDAQ", "TESLA", "APL") ):
    print(idx, val)

{'Rayan': 'Active'}
0 NASDAQ
1 TESLA
2 APL
DASR
DREC
PAMI


### Как удалить дубликаты из стурктуры данных

In [8]:
facts = ("PAMI", "DREC", "DASR", "DASR")
for f in sorted(set(facts)):
     print(f)

DASR
DREC
PAMI


### Sugar

In [30]:
a = 2 if 1 > 0 else -2
a   

2

### Map()

In [29]:
f = lambda arg: arg * arg

## Map returns an iterator.
## map(function, iteratable1, iteratable2, ...)
for item in map(lambda x: x ** 2, [2, 3, 4]):
    print(item, sep=' ')

### Built-in usage
base_numbers = [2, 4, 6, 8, 10, 12, 14, 16]
powers = [1, 2, 3, 4, 5]
numbers_powers = list(map(pow, base_numbers, powers))    
print(numbers_powers)
###    

print(list( map(lambda x: x**2, range(1,11,2)) ))
print( list( map( lambda a, b: a**2 - b**2, range(1,11), [2, 5, 7, 3] ) ) ) 

4
9
16
[2, 16, 216, 4096, 100000]
[1, 9, 25, 49, 81]
[-3, -21, -40, 7]


### Filter()

In [3]:
# filter(predicate, iterable) - only if pred is true
stuff = ['A', 'B', 'C', 'D', 'a', 'k', 0, 0]
filtered = list( filter(lambda x: x != 0, stuff) )
print(filtered)

['A', 'B', 'C', 'D', 'a', 'k']


## Numpy

In [57]:
import numpy as np
# np.ndarray, массивы однородны, т.е либо все int32, либо float64.
# Точку после чисел (1.) ставим, потому что хотим именно float-массив.
# Одной точки достаточно, но лучше все.
arrayA = np.array([ [1., 0, 0],
           [0, 1, 2]
        ])
print(arrayA.dtype)

float64


In [42]:
a = np.arange(15).reshape(3, 5) ## Num of elements (i.e. 15) must be specific.
print(a)
print(a.shape) ## (rows, cols) в 2D
print(a.ndim)  ## Степени свободы
print(a.size)  ## rows * cols = кол-во элементов

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
15


In [60]:
b = np.array( [[1, 2, 3], [4, 5, 6]] )
print(b.shape)
c = np.array( ((1, 2, 3), (4, 5, 6)) )
print(c.shape)
d = np.array( [ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ] )
print(d.ndim, d.shape) # shape - сколько вариантов на каждом шаге при поиске элемента
# В какой из [] ты? Внутри? Ещё внутри?

# Indeces
print(d[0][1][2], d[0, 1, 2], sep=' ')

(2, 3)
(2, 3)
3 (2, 2, 3)
6 6


In [65]:
zero = np.zeros( [3, 4] )
print(zero)
one  = np.ones ( (4, 5) )
print(one)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [77]:
## ARANGE - откуда, куда, с каким шагом (кол-во автомат.). [a, b), как range.
print(np.arange(1, 11, 1))  ## Возвр. np.ndarray
print(list(np.arange(0, 0.8, 0.2)))

## LINSPACE - откуда, куда, сколько хотим в итоге (шаг автомат.). [a; b]
print(np.linspace(1, 10, 10))

[ 1  2  3  4  5  6  7  8  9 10]
[0.0, 0.2, 0.4, 0.6000000000000001]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Операции

In [95]:
a = np.array([ [1, 2], [3, 4] ])
b = np.arange(4).reshape(2, 2) ## = np.arange(0, 4, 1)
print(a)
print(b)
print() ## Операции поэлементны
print(a - b)
print(b ** 2)
print(a > 2)
print(np.exp(a))
print() ## Матричное
print(a @ b) ## = np.dot(a, b), a.dot(b)
print(a * b) ## c_i_j = a_i_j * b_i_j

[[1 2]
 [3 4]]
[[0 1]
 [2 3]]

[[1 1]
 [1 1]]
[[0 1]
 [4 9]]
[[False False]
 [ True  True]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

[[ 4  7]
 [ 8 15]]
[[ 0  2]
 [ 6 12]]


In [92]:
print(a.sum())
print(a.min())
print(a.max())

10
1
4


In [94]:
print(b.sum(axis=0))     # sum of each column
print(b.sum(axis=1))
print(b.min(axis=1))     # min of each row
print(b.cumsum(axis=1))  # cumulative sum along each row ##??????????????

[2 4]
[1 5]
[0 2]
[[0 1]
 [2 5]]


In [96]:
## TODO: Одномерные массивы можно индексировать, нарезать и итерировать, как встроенные типы последовательностей Python (например, списки)

In [7]:
M = [[0] * 5] * 3
print(M)
M[0][3] = 1
M

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 0, 0, 1, 0]]